# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from landing/center.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class center(genpy.Message):
  _md5sum = "435bfc8b0a9a23f7ba5ab3357a37f574"
  _type = "landing/center"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint32 width
uint32 height
float64 x
float64 y
bool iffind
"""
  __slots__ = ['width','height','x','y','iffind']
  _slot_types = ['uint32','uint32','float64','float64','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       width,height,x,y,iffind

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(center, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.width is None:
        self.width = 0
      if self.height is None:
        self.height = 0
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.iffind is None:
        self.iffind = False
    else:
      self.width = 0
      self.height = 0
      self.x = 0.
      self.y = 0.
      self.iffind = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I2dB().pack(_x.width, _x.height, _x.x, _x.y, _x.iffind))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 25
      (_x.width, _x.height, _x.x, _x.y, _x.iffind,) = _get_struct_2I2dB().unpack(str[start:end])
      self.iffind = bool(self.iffind)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I2dB().pack(_x.width, _x.height, _x.x, _x.y, _x.iffind))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 25
      (_x.width, _x.height, _x.x, _x.y, _x.iffind,) = _get_struct_2I2dB().unpack(str[start:end])
      self.iffind = bool(self.iffind)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I2dB = None
def _get_struct_2I2dB():
    global _struct_2I2dB
    if _struct_2I2dB is None:
        _struct_2I2dB = struct.Struct("<2I2dB")
    return _struct_2I2dB
